
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author solit
 */
public class guru extends javax.swing.JFrame {
     private Connection Con;

    /**
     * Creates new form guru
     */
    public guru() {
        initComponents();
        KoneksiDatabase();
    }
      private void KoneksiDatabase() {
        try {
    
             //Menentukan Driver Database
           Class.forName("com.mysql.jdbc.Driver");
             //Untuk mengkoneksikan DB ke Driver 
             Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah", "root", "");
             //pesan Koneksi Berhasil//
             JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        }  catch (HeadlessException | ClassNotFoundException | SQLException e) {
             //pesan Koneksi Gagal//
             System.out.println("Koneksi Gagal"+ e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nama_guru = new javax.swing.JLabel();
        mata_pelajaran = new javax.swing.JLabel();
        tguru = new javax.swing.JTextField();
        tpelajaran = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        cansel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        nama_guru.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        nama_guru.setText("Nama Guru :");

        mata_pelajaran.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        mata_pelajaran.setText("Mata Pelajaran :");

        tguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tguruActionPerformed(evt);
            }
        });

        tpelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpelajaranActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cansel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cansel.setText("Cansel");
        cansel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canselActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guru.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save)
                        .addGap(7, 7, 7)
                        .addComponent(cansel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama_guru)
                            .addComponent(mata_pelajaran))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tguru, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(tpelajaran))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_guru)
                    .addComponent(tguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mata_pelajaran)
                    .addComponent(tpelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(cansel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String nama_guru = tguru.getText();
       String mata_pelajaran = tpelajaran.getText();
       try{
             String sql = "INSERT INTO guru (nama,mata_pelajaran) VALUES (?,?)";
             PreparedStatement state = this.Con.prepareStatement(sql);
             state.setString(1,nama_guru);
             state.setString(2,mata_pelajaran);
             
             int result = state.executeUpdate();
             if(result > 0){
                 menu mnu= new menu ();
                 mnu.setVisible(true);
                 this.dispose();
                 JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                 new menu ().setVisible(true);
                 this.dispose();
             } else {
                 JOptionPane.showMessageDialog(null, "Data gagal");
             }
             
             
         }catch(SQLException er){
             System.out.println(er);
         }
       
        menu mnu= new menu ();
        mnu.setVisible(true);
        this.dispose();
       JOptionPane.showMessageDialog(null, "Data Guru Berhasil Disimpan");
    }//GEN-LAST:event_saveActionPerformed

    private void tguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tguruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tguruActionPerformed

    private void canselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canselActionPerformed
        tguru.setText("");
        tpelajaran.setText("");
        tguru.requestFocus();
    }//GEN-LAST:event_canselActionPerformed

    private void tpelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpelajaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpelajaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cansel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mata_pelajaran;
    private javax.swing.JLabel nama_guru;
    private javax.swing.JButton save;
    private javax.swing.JTextField tguru;
    private javax.swing.JTextField tpelajaran;
    // End of variables declaration//GEN-END:variables
}
